apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: le-clusterissuer
  namespace: cert-manager
spec:
  acme:
    email: r1nzl3r-bl4ck@protonmail.com
    privateKeySecretRef:
      name: le-clusterissuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        acmedns:
          host: https://auth.acme-dns.io
          accountSecretRef:
            name: acme-dns
            key: acmedns.json
#      http01:
#       ingress:
#         class:  nginx
---
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: le-staging-clusterissuer
  namespace: cert-manager
spec:
  acme:
    email: r1nzl3r-bl4ck@protonmail.com
    privateKeySecretRef:
      name: le-staging-clusterissuer
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        acmedns:
          host: https://auth.acme-dns.io
          accountSecretRef:
            name: acme-dns
            key: acmedns.json
#      http01:
#       ingress:
#         class:  nginx
